name: test

on:   
  push:  
    branches: [2-installer-no-longer-installing-on-linux]
  pull_request:
    
permissions: 
  contents: read

jobs: 
  test-install: 
    strategy:
      matrix:
        os:
          - ubuntu:jammy
          - ubuntu:focal
          - ubuntu:bionic
          - ubuntu:xenial
          - debian:bullseye
          - debian:buster
    runs-on: ubuntu-latest
    container: 
      image: ${{ matrix.os }}
    steps:
      - name: Install git apt
        run: |
          apt-get update
          apt-get install -y git
        if: ${{ contains('ubuntu', matrix.os ) || contains('debian', matrix.os ) }}
      - uses: actions/checkout@v3
      - run: git config --system --add safe.directory $GITHUB_WORKSPACE
      - run: ./install_collector.sh